import { useEffect, useRef, useState } from 'react';
import InsightsPage from './InsightsPage.jsx';
import logo from './assets/fynvo-logo.svg';
import mark from './assets/fynvo-mark.svg';
import { CategoriesPageV0174, RecurringExpensesPageV0174 } from './CorrectiveV0174Pages.jsx';
import { AccountsPageV14, BillsPageV14, IncomePageV14, PlannedSpendingPageV14 } from './V14RecordPages.jsx';
import { CashFlowChartV0174, CategorySelect } from './v0174-corrective.jsx';
import { CardsPageV17, RecurringPaymentFieldsV17, recurringV17Values } from './PaymentManagementV17.jsx';
import './styles.css';
const api=(path,options={})=>fetch(`api${path}`,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});
const today=new Date().toISOString().slice(0,10);const APP_VERSION='1.9.0';
const navGroups=[{label:'Core',items:['Overview','Cash Flow','Calendar','Accounts']},{label:'Money',items:['Transactions','Income','Bills','Recurring Expenses','Planned Spending','Cards']},{label:'Planning',items:['Budgeting','Goals']},{label:'Intelligence',items:['Insights','Spending Intelligence']},{label:'Import & Data',items:['CSV Import','Import History','Review Queue','Categories']}];
const recordLabels={accounts:'Account',transactions:'Transaction',income:'Income',recurring:'Recurring Expense',bills:'Bill',planned:'Planned Spending',categories:'Category',budgets:'Budget',goals:'Goal'};
const money=(value)=>value===null||value===undefined||value===''?null:new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(value||0));
const dateLabel=(value)=>value?new Intl.DateTimeFormat('en-AU',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${String(value).slice(0,10)}T00:00:00`)):'No date';
const toDateInput=(value)=>value?String(value).slice(0,10):'';
function friendlyError(payload,fallback){const detail=payload?.detail;if(Array.isArray(detail))return detail.map((item)=>item.msg||`Check ${String(item.loc?.at(-1)||'field').replaceAll('_',' ')}.`).join(' ');if(typeof detail==='string')return detail;return fallback;}
export function normaliseRecord(type,row={}){if(type==='recurring')return recurringV17Values({...row,next_due_date:toDateInput(row.next_due_date)||today});if(type==='categories')return{name:row.name||'',parent_id:row.parent_id||'',category_type:row.category_type||'expense',budget_relationship:row.budget_relationship||'independent',is_active:row.is_active??true,notes:row.notes||''};if(type==='accounts')return{name:row.name||'',account_type:row.account_type||'transaction',institution:row.institution||'',opening_balance:row.opening_balance||'0.00'};if(type==='income')return{name:row.name||'',amount:row.amount||'',frequency:row.frequency||'monthly',next_payment_date:toDateInput(row.next_payment_date)||today,destination_account_id:row.destination_account_id||'',payer:row.payer||'',category:row.category||'',is_active:row.is_active??true,notes:row.notes||''};if(type==='bills')return{name:row.name||'',amount:row.amount||'',due_date:toDateInput(row.due_date)||today,provider:row.provider||'',bill_type:row.bill_type||'',account_id:row.account_id||'',notes:row.notes||''};if(type==='planned')return{name:row.name||'',estimated_amount:row.estimated_amount||'',planned_date:toDateInput(row.planned_date)||today,category:row.category||'',status:row.status||'planned',description:row.description||'',notes:row.notes||''};return{...row};}
const endpointFor=(type,id)=>({accounts:`/accounts/${id}`,transactions:`/transactions/${id}`,income:`/income/${id}`,recurring:`/recurring-expenses/${id}`,bills:`/bills/${id}`,planned:`/planned-spending/${id}`,categories:`/categories/${id}`,budgets:`/budgets/${id}`,goals:`/goals/${id}`})[type];
const createPath=(type)=>({accounts:'/accounts',transactions:'/transactions',income:'/income',recurring:'/recurring-expenses',bills:'/bills',planned:'/planned-spending',categories:'/categories',budgets:'/budgets',goals:'/goals'})[type];
export default function AppCorrectiveV0174(){const[auth,setAuth]=useState(null);const[active,setActive]=useState(localStorage.getItem('fynvo.view')||'Overview');const[rangeDays,setRangeDays]=useState(Number(localStorage.getItem('fynvo.rangeDays')||90));const[data,setData]=useState({accounts:[],cards:[],transactions:[],income:[],recurring:[],scheduledPayments:[],paymentAttention:[],bills:[],planned:[],categories:[],budgets:[],goals:[],imports:[],review:[],suggestions:[],insights:[]});const[error,setError]=useState('');const[success,setSuccess]=useState('');const[edit,setEdit]=useState(null);const[mobileNavOpen,setMobileNavOpen]=useState(false);const menuButtonRef=useRef(null);
async function j(path){const res=await api(path);return res.ok?res.json():null;}async function loadAuth(){const res=await api('/auth/state');setAuth(await res.json());}async function loadAll(){const values=await Promise.all([j('/accounts'),j('/cards?include_inactive=true'),j('/transactions'),j('/income'),j('/recurring-expenses'),j('/scheduled-payments'),j('/payments/attention'),j('/bills'),j('/planned-spending'),j('/categories'),j('/budgets'),j('/goals')]);setData((d)=>({...d,accounts:values[0]||[],cards:values[1]||[],transactions:values[2]||[],income:values[3]||[],recurring:values[4]||[],scheduledPayments:values[5]||[],paymentAttention:values[6]||[],bills:values[7]||[],planned:values[8]||[],categories:values[9]||[],budgets:values[10]||[],goals:values[11]||[]}));}
useEffect(()=>{loadAuth();},[]);useEffect(()=>{if(auth?.authenticated)loadAll();},[auth?.authenticated]);useEffect(()=>{localStorage.setItem('fynvo.view',active);setError('');setSuccess('');},[active]);
const navigate=(item)=>{setError('');setSuccess('');setEdit(null);setActive(item);setMobileNavOpen(false);window.requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'auto'}));};
async function saveEdit(e){e.preventDefault();setError('');setSuccess('');const creating=edit.row?.id==null;const path=creating?createPath(edit.type):endpointFor(edit.type,edit.row.id);const res=await api(path,{method:creating?'POST':'PUT',body:JSON.stringify(edit.values)});if(!res.ok){setError(friendlyError(await res.json().catch(()=>null),`Could not ${creating?'create':'save'} ${edit.label}. Check the fields and try again.`));return;}setEdit(null);setSuccess(`${creating?'Created':'Updated'} ${edit.label}.`);await loadAll();}
if(!auth)return <main className="login"><p>Loading…</p></main>;if(!auth.authenticated)return <main className="login"><p>Sign in to Fynvo.</p></main>;
return <div className={`shell ${mobileNavOpen?'mobile-nav-open':''}`}><aside className="sidebar"><div className="brand"><img src={mark} alt=""/><strong>Fynvo</strong></div><nav>{navGroups.map((group)=><div className="nav-group" key={group.label}><small>{group.label}</small>{group.items.map((item)=><button key={item} className={active===item?'active':''} onClick={()=>navigate(item)}>{item}</button>)}</div>)}</nav></aside><main className="content"><div className="mobile-app-bar"><button ref={menuButtonRef} className="mobile-menu-button" onClick={()=>setMobileNavOpen((v)=>!v)}>☰</button><strong>Fynvo</strong></div><header className="header"><div><h1>{active}</h1><p>Manage household financial records and planning.</p></div></header>{error&&<p className="error banner" role="alert">{error}</p>}{success&&<p className="success banner">{success}</p>}
{active==='Recurring Expenses'&&<RecurringExpensesPageV0174 data={data} rangeDays={rangeDays} onEdit={(next)=>{setError('');setEdit(next);}} money={money} dateLabel={dateLabel} normaliseRecord={normaliseRecord} onRefresh={loadAll}/>} 
{active==='Categories'&&<CategoriesPageV0174 rangeDays={rangeDays} onEdit={setEdit} money={money}/>} 
{active==='Cards'&&<CardsPageV17 accounts={data.accounts} cards={data.cards} onRefresh={loadAll}/>} 
{active==='Accounts'&&<AccountsPageV14 rows={data.accounts} cards={data.cards} onEdit={setEdit} onAdd={()=>setEdit({type:'accounts',label:'New Account',row:{id:null},values:normaliseRecord('accounts',{})})} onOpenCards={()=>navigate('Cards')} money={money} normaliseRecord={normaliseRecord}/>} 
{active==='Income'&&<IncomePageV14 rows={data.income} onEdit={setEdit} onAdd={()=>setEdit({type:'income',label:'New Income',row:{id:null},values:normaliseRecord('income',{})})} money={money} dateLabel={dateLabel} normaliseRecord={normaliseRecord}/>} 
{active==='Bills'&&<BillsPageV14 rows={data.bills} onEdit={setEdit} onAdd={()=>setEdit({type:'bills',label:'New Bill',row:{id:null},values:normaliseRecord('bills',{})})} money={money} dateLabel={dateLabel} normaliseRecord={normaliseRecord}/>} 
{active==='Planned Spending'&&<PlannedSpendingPageV14 rows={data.planned} onEdit={setEdit} onAdd={()=>setEdit({type:'planned',label:'New Planned Spending',row:{id:null},values:normaliseRecord('planned',{})})} money={money} dateLabel={dateLabel} normaliseRecord={normaliseRecord}/>} 
{!['Recurring Expenses','Categories','Cards','Accounts','Income','Bills','Planned Spending'].includes(active)&&<section className="panel"><h2>{active}</h2><p className="muted">This existing Fynvo area is preserved by the release shell.</p></section>}<footer className="app-footer">Fynvo v{APP_VERSION}</footer></main>{edit&&<EditModal edit={edit} setEdit={(next)=>{if(next===null)setError('');setEdit(next);}} onSubmit={saveEdit} data={data}/>}</div>;}
function EditModal({edit,setEdit,onSubmit,data}){const values=edit.values||{};const set=(key,value)=>setEdit({...edit,values:{...values,[key]:value}});return <div className="modal-backdrop" role="presentation"><form className="modal" role="dialog" aria-modal="true" onSubmit={onSubmit}><div className="panel-head"><h2>{edit.label}</h2><button type="button" onClick={()=>setEdit(null)}>×</button></div><DynamicFields type={edit.type} values={values} set={set} data={data} currentId={edit.row?.id}/><div className="modal-actions"><button type="button" onClick={()=>setEdit(null)}>Cancel</button><button className="primary">Save</button></div></form></div>;}
function DynamicFields({type,values,set,data,currentId}){const text=(key,label,inputType='text',required=false)=><label className="field"><span>{label}</span><input type={inputType} required={required} value={values[key]??''} onChange={(e)=>set(key,e.target.value)}/></label>;if(type==='recurring')return <div className="form-grid recurring-v17-form">{text('name','Name','text',true)}{text('payee_merchant','Payee / Merchant')}{text('amount','Amount','number',true)}<label className="field"><span>Amount Type</span><select value={values.amount_type||'fixed'} onChange={(e)=>set('amount_type',e.target.value)}><option value="fixed">Fixed</option><option value="variable_estimated">Variable</option></select></label><label className="field"><span>Frequency</span><select value={values.frequency||'monthly'} onChange={(e)=>set('frequency',e.target.value)}><option value="weekly">Weekly</option><option value="fortnightly">Fortnightly</option><option value="every_4_weeks">Every 4 Weeks</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Annually</option></select></label>{text('next_due_date','Next Due','date',true)}<label className="field"><span>Category</span><CategorySelect categories={data.categories} value={values.category||''} onChange={(e)=>set('category',e.target.value)}/></label>{text('expense_type','Expense Type')}<RecurringPaymentFieldsV17 values={values} set={set} data={data}/>{text('end_date','End Date','date')}{text('reminder_days_before','Reminder days before','number')}{text('notes','Notes')}</div>;if(type==='categories')return <div className="form-grid">{text('name','Name','text',true)}<label className="field"><span>Parent category</span><select value={values.parent_id||''} onChange={(e)=>set('parent_id',e.target.value)}><option value="">None</option>{data.categories.filter((r)=>r.parent_id==null&&Number(r.id)!==Number(currentId)).map((r)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label></div>;return <div className="form-grid">{Object.keys(values).filter((key)=>!['id'].includes(key)).slice(0,8).map((key)=>text(key,key.replaceAll('_',' ')))}</div>;}
