import { useEffect, useRef, useState } from 'react';
import InsightsPage from './InsightsPage.jsx';
import logo from './assets/fynvo-logo.svg';
import mark from './assets/fynvo-mark.svg';
import { CategoriesPageV0174, RecurringExpensesPageV0174 } from './CorrectiveV0174Pages.jsx';
import { AccountsPageV14, BillsPageV14, IncomePageV14, PlannedSpendingPageV14 } from './V14RecordPages.jsx';
import { APP_VERSION_V0174, CashFlowChartV0174, CategorySelect } from './v0174-corrective.jsx';
import { CardsPageV17, PaymentReconciliationV17, PaymentsAttentionV17, RecurringPaymentFieldsV17, recurringV17Values } from './PaymentManagementV17.jsx';
import './styles.css';

const api = (path, options = {}) => fetch(`api${path}`, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options });
const today = new Date().toISOString().slice(0, 10);
const APP_VERSION = '1.7.0';
const navGroups = [
  { label: 'Core', items: ['Overview', 'Cash Flow', 'Calendar', 'Accounts'] },
  { label: 'Money', items: ['Transactions', 'Income', 'Bills', 'Recurring Expenses', 'Planned Spending', 'Cards'] },
  { label: 'Planning', items: ['Budgeting', 'Goals'] },
  { label: 'Intelligence', items: ['Insights', 'Spending Intelligence'] },
  { label: 'Import & Data', items: ['CSV Import', 'Import History', 'Review Queue', 'Categories'] },
];
const accountTypeOptions = [
  ['transaction', 'Transaction Account'], ['savings', 'Savings Account'], ['offset', 'Offset Account'], ['credit_card', 'Credit Card'], ['cash', 'Cash'], ['mortgage', 'Mortgage'], ['personal_loan', 'Personal Loan'], ['car_loan', 'Car Loan'], ['line_of_credit', 'Line of Credit'], ['investment', 'Investment Account'], ['superannuation', 'Superannuation'], ['other_asset', 'Other Asset'], ['other_liability', 'Other Liability'],
];
const recordLabels = { accounts: 'Account', transactions: 'Transaction', income: 'Income', recurring: 'Recurring Expense', bills: 'Bill', planned: 'Planned Spending', categories: 'Category', budgets: 'Budget', goals: 'Goal' };
const quickAddOptions = [
  ['transactions', 'Transaction', 'Record a purchase, payment or deposit.'],
  ['income', 'Income', 'Add a recurring or expected income source.'],
  ['recurring', 'Recurring Expense', 'Add a repeating household commitment.'],
  ['bills', 'Bill', 'Add a bill or one-off obligation.'],
  ['planned', 'Planned Spending', 'Add a future planned purchase or expense.'],
  ['accounts', 'Account', 'Add another financial account.'],
  ['goals', 'Goal', 'Add a savings, purchase or debt goal.'],
];
const accountTypeLabel = (value) => accountTypeOptions.find(([id]) => id === value)?.[1] || (value === 'vehicle_loan' ? 'Car Loan' : value?.replaceAll('_', ' ') || 'Account');
const horizonOptions = [
  { label: 'Next 7 days', value: 7 }, { label: 'Next 30 days', value: 30 }, { label: 'Next 90 days', value: 90 }, { label: 'Next 6 months', value: 184 }, { label: 'Next 12 months', value: 365 },
];
const money = (value) => value === null || value === undefined || value === '' ? null : new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD' }).format(Number(value || 0));
const dateLabel = (value) => value ? new Intl.DateTimeFormat('en-AU', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${String(value).slice(0, 10)}T00:00:00`)) : 'No date';
const amountClass = (value) => Number(value || 0) >= 0 ? 'positive' : 'negative';
const parseAmount = (value) => Number(value || 0);
const greetingForNow = () => { const hour = new Date().getHours(); if (hour < 12) return 'Good morning'; if (hour < 17) return 'Good afternoon'; return 'Good evening'; };
const Field = ({ label, children, error, className = '', ...props }) => <label className={`field ${className} ${error ? 'field-error' : ''}`.trim()}><span>{label}</span>{children || <input {...props}/>} {error && <small className="field-error-message">{error}</small>}</label>;
const Badge = ({ children, tone = '' }) => <span className={`badge ${tone}`}>{children}</span>;
const Empty = ({ title, children, action }) => <div className="empty"><strong>{title}</strong><p>{children}</p>{action}</div>;
const toDateInput = (value) => value ? String(value).slice(0, 10) : '';

function friendlyError(payload, fallback) {
  const detail = payload?.detail;
  if (Array.isArray(detail)) {
    const messages = detail.map((item) => { const field = item.loc?.slice(-1)[0]; if (field === 'account_id' || field === 'destination_account_id') return 'Choose a valid account.'; if (item.type === 'missing') return `${String(field || 'A required field').replaceAll('_', ' ')} is required.`; if (field) return `Check ${String(field).replaceAll('_', ' ')}.`; return null; }).filter(Boolean);
    return [...new Set(messages)].join(' ') || fallback;
  }
  if (typeof detail === 'string') return detail;
  return fallback;
}

export function normaliseRecord(type, row = {}) {
  if (type === 'accounts') return { name: row.name || '', account_type: row.account_type || 'transaction', institution: row.institution || '', opening_balance: row.opening_balance || '0.00', description: row.description || '', account_suffix: row.account_suffix || '', icon: row.icon || '', color: row.color || '' };
  if (type === 'transactions') return { account_id: row.account_id || '', date: toDateInput(row.date || row.transaction_date) || today, amount: row.amount || '', transaction_type: row.transaction_type || 'expense', description: row.description || '', merchant: row.merchant || '', category: row.category || '', notes: row.notes || '', status: row.status || 'cleared' };
  if (type === 'income') return { name: row.name || '', amount: row.amount || '', frequency: row.frequency || 'monthly', next_payment_date: toDateInput(row.next_payment_date) || today, destination_account_id: row.destination_account_id || '', payer: row.payer || '', category: row.category || '', is_active: row.is_active ?? true, notes: row.notes || '', effective_from: '' };
  if (type === 'recurring') return recurringV17Values({ ...row, next_due_date: toDateInput(row.next_due_date) || today });
  if (type === 'bills') return { name: row.name || '', provider: row.provider || '', bill_type: row.bill_type || '', priority: row.priority || 'normal', amount: row.amount || '', due_date: toDateInput(row.due_date) || today, account_id: row.account_id || '', paid_through_date: toDateInput(row.paid_through_date), status: row.status || '', notes: row.notes || '', recurring_expense_id: row.recurring_expense_id || '' };
  if (type === 'planned') return { name: row.name || '', description: row.description || '', estimated_amount: row.estimated_amount || '', planned_date: toDateInput(row.planned_date) || today, category: row.category || '', account_id: row.account_id ?? null, priority: row.priority || 'medium', status: row.status || 'planned', include_in_forecast: row.include_in_forecast ?? true, notes: row.notes || '' };
  if (type === 'categories') return { name: row.name || '', parent_id: row.parent_id || '', icon: row.icon || '', color: row.color || '', category_type: row.category_type || 'expense', budget_relationship: row.budget_relationship || 'independent', is_active: row.is_active ?? true, notes: row.notes || '' };
  if (type === 'budgets') return { name: row.name || '', category_id: row.category_id || '', category_name: row.category_name || '', direction: row.direction || 'expense', period: row.period || 'monthly', amount: row.amount || '', allocation_strategy: row.allocation_strategy || 'spend_during_period', relationship_mode: row.relationship_mode || 'independent', anchor_date: toDateInput(row.anchor_date) || today, start_date: toDateInput(row.start_date) || today, end_date: toDateInput(row.end_date), rollover_enabled: row.rollover_enabled ?? false, negative_rollover_enabled: row.negative_rollover_enabled ?? false, is_active: row.is_active ?? true, notes: row.notes || '', effective_from: '' };
  if (type === 'goals') return { name: row.name || '', description: row.description || '', goal_type: row.goal_type || 'savings', target_amount: row.target_amount || '', current_amount: row.current_amount || '', start_date: toDateInput(row.start_date) || today, target_date: toDateInput(row.target_date), priority: row.priority || 'medium', contribution_frequency: row.contribution_frequency || 'monthly', contribution_amount: row.contribution_amount || '', status: row.status || 'active', notes: row.notes || '' };
  return { ...row };
}

function endpointFor(type, id) { return ({ accounts: `/accounts/${id}`, transactions: `/transactions/${id}`, income: `/income/${id}`, recurring: `/recurring-expenses/${id}`, bills: `/bills/${id}`, planned: `/planned-spending/${id}`, categories: `/categories/${id}`, budgets: `/budgets/${id}`, goals: `/goals/${id}` })[type]; }
function createPath(type) { return ({ accounts: '/accounts', transactions: '/transactions', income: '/income', recurring: '/recurring-expenses', bills: '/bills', planned: '/planned-spending', categories: '/categories', budgets: '/budgets', goals: '/goals' })[type]; }
function forecastSource(event, data) { const mapping = { income: ['income', data.income], recurring_expense: ['recurring', data.recurring], bill: ['bills', data.bills], planned_spending: ['planned', data.planned] }; const matched = mapping[event?.source_type]; if (!matched) return { type: null, record: null }; const [type, rows] = matched; return { type, record: (rows || []).find((row) => Number(row.id) === Number(event.source_id)) || null }; }

export default function AppCorrectiveV0174() {
  const [auth, setAuth] = useState(null);
  const [active, setActive] = useState(localStorage.getItem('fynvo.view') || 'Overview');
  const [rangeDays, setRangeDays] = useState(Number(localStorage.getItem('fynvo.rangeDays') || 90));
  const [form, setForm] = useState({ username: '', display_name: '', password: '' });
  const [data, setData] = useState({ accounts: [], cards: [], transactions: [], income: [], recurring: [], scheduledPayments: [], paymentAttention: [], bills: [], planned: [], categories: [], budgets: [], goals: [], imports: [], review: [], suggestions: [], insights: [], financialHealth: null, budgetAnalysis: null, forecast: null, command: null });
  const [dashboardLoading, setDashboardLoading] = useState(true);
  const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [edit, setEdit] = useState(null); const [quick, setQuick] = useState(null); const [quickMenuOpen, setQuickMenuOpen] = useState(false); const [detail, setDetail] = useState(null); const [greeting, setGreeting] = useState(() => greetingForNow()); const [mobileNavOpen, setMobileNavOpen] = useState(false); const [isMobile, setIsMobile] = useState(() => window.matchMedia('(max-width: 980px)').matches);
  const menuButtonRef = useRef(null); const closeButtonRef = useRef(null); const commandRequestRef = useRef(0); const initialLoadedRef = useRef(false);
  const [importState, setImportState] = useState({ filename: '', account_id: '', csv_text: '', source_name: 'Australian bank CSV', mapping: { date: 'Date', description: 'Description', debit: 'Debit', credit: 'Credit', amount: 'Amount' }, preview: null });

  async function loadAuth() { const res = await api('/auth/state'); setAuth(await res.json()); }
  async function j(path) { const res = await api(path); return res.ok ? await res.json() : null; }
  async function refreshDashboard(days = rangeDays) { const requestId = ++commandRequestRef.current; setDashboardLoading(true); try { const command = await j(`/dashboard/command-centre?range_days=${days}`); if (requestId !== commandRequestRef.current) return; setData((current) => ({ ...current, command })); } finally { if (requestId === commandRequestRef.current) setDashboardLoading(false); } }
  async function loadSupportingData() {
    const [accounts, cards, transactions, income, recurring, scheduledPayments, paymentAttention, bills, planned, categories, budgets, goals, imports, review, suggestions, insights, financialHealth, budgetAnalysis, forecast] = await Promise.all([
      j('/accounts'), j('/cards?include_inactive=true'), j('/transactions'), j('/income'), j('/recurring-expenses'), j('/scheduled-payments'), j('/payments/attention'), j('/bills'), j('/planned-spending'), j('/categories'), j('/budgets'), j('/goals'), j('/imports/history'), j('/reconciliation/review-queue'), j('/intelligence/suggestions'), j(`/insights?horizon_days=${rangeDays}&refresh=false`), j(`/insights/financial-health?horizon_days=${rangeDays}`), j('/budgets/analysis'), j(`/forecast?mode=expected&horizon=${rangeDays}d`),
    ]);
    setData((current) => ({ ...current, accounts: accounts || [], cards: cards || [], transactions: transactions || [], income: income || [], recurring: recurring || [], scheduledPayments: scheduledPayments || [], paymentAttention: paymentAttention || [], bills: bills || [], planned: planned || [], categories: categories || [], budgets: budgets || [], goals: goals || [], imports: imports || [], review: review || [], suggestions: suggestions || [], insights: insights || [], financialHealth, budgetAnalysis, forecast }));
  }
  async function loadAll() { await Promise.allSettled([refreshDashboard(rangeDays), loadSupportingData()]); }

  useEffect(() => { loadAuth(); }, []);
  useEffect(() => { if (!auth?.authenticated) return; if (!initialLoadedRef.current) { initialLoadedRef.current = true; loadAll(); return; } refreshDashboard(rangeDays); }, [auth?.authenticated, rangeDays]);
  useEffect(() => { localStorage.setItem('fynvo.view', active); setSuccess(''); }, [active]);
  useEffect(() => { localStorage.setItem('fynvo.rangeDays', String(rangeDays)); }, [rangeDays]);
  useEffect(() => { if (!success) return undefined; const timer = window.setTimeout(() => setSuccess(''), 4000); return () => window.clearTimeout(timer); }, [success]);
  useEffect(() => { const syncGreeting = () => setGreeting(greetingForNow()); syncGreeting(); const timer = window.setInterval(syncGreeting, 60000); window.addEventListener('focus', syncGreeting); document.addEventListener('visibilitychange', syncGreeting); return () => { window.clearInterval(timer); window.removeEventListener('focus', syncGreeting); document.removeEventListener('visibilitychange', syncGreeting); }; }, []);
  useEffect(() => { const media = window.matchMedia('(max-width: 980px)'); const sync = (event) => { setIsMobile(event.matches); setMobileNavOpen(false); document.body.style.overflow = ''; }; media.addEventListener?.('change', sync); return () => media.removeEventListener?.('change', sync); }, []);
  useEffect(() => { if (!isMobile) return undefined; const previousOverflow = document.body.style.overflow; document.body.style.overflow = mobileNavOpen ? 'hidden' : previousOverflow; if (mobileNavOpen) window.requestAnimationFrame(() => closeButtonRef.current?.focus({ preventScroll: true })); return () => { document.body.style.overflow = previousOverflow; }; }, [mobileNavOpen, isMobile]);
  useEffect(() => { const onKeyDown = (event) => { if (event.key === 'Escape') { if (detail) setDetail(null); else if (quickMenuOpen) setQuickMenuOpen(false); else if (mobileNavOpen) { event.preventDefault(); setMobileNavOpen(false); window.requestAnimationFrame(() => menuButtonRef.current?.focus({ preventScroll: true })); } } }; document.addEventListener('keydown', onKeyDown); return () => document.removeEventListener('keydown', onKeyDown); }, [mobileNavOpen, quickMenuOpen, detail]);

  async function submitAuth(e) { e.preventDefault(); setError(''); const payload = auth?.setup_required ? { username: form.username, display_name: form.display_name || form.username, password: form.password } : { username: form.username, password: form.password }; const res = await api(auth?.setup_required ? '/auth/setup' : '/auth/login', { method: 'POST', body: JSON.stringify(payload) }); if (res.ok) { setMobileNavOpen(false); await loadAuth(); } else setError('Sign-in failed. Check your username and password.'); }
  async function logout() { await api('/auth/logout', { method: 'POST' }); setMobileNavOpen(false); setAuth({ authenticated: false, setup_required: false, user: null }); }
  async function saveEdit(e) { e.preventDefault(); setError(''); setSuccess(''); const creating = edit.row?.id === null || edit.row?.id === undefined; const path = creating ? createPath(edit.type) : endpointFor(edit.type, edit.row.id); const res = await api(path, { method: creating ? 'POST' : 'PUT', body: JSON.stringify(edit.values) }); if (!res.ok) { setError(friendlyError(await res.json().catch(() => null), `Could not ${creating ? 'create' : 'save'} ${edit.label}. Check the fields and try again.`)); return; } const message = `${creating ? edit.label.replace(/^New /, '') + ' created.' : edit.label + ' updated.'}`; setEdit(null); setSuccess(message); await loadAll(); }
  async function createRecord(type, values) { setError(''); setSuccess(''); const res = await api(createPath(type), { method: 'POST', body: JSON.stringify(values) }); if (res.ok) { setQuick(null); setSuccess(`${recordLabels[type] || 'Record'} created.`); await loadAll(); } else setError(friendlyError(await res.json().catch(() => null), 'Could not create this record. Check the fields and try again.')); }
  async function previewImport(e) { e.preventDefault(); const res = await api('/imports/preview', { method: 'POST', body: JSON.stringify(importState) }); if (res.ok) setImportState({ ...importState, preview: await res.json() }); else setError('CSV preview failed. Check the account, headers and mapping.'); }
  async function commitImport() { const res = await api('/imports/commit', { method: 'POST', body: JSON.stringify(importState) }); if (res.ok) { setImportState({ ...importState, preview: await res.json() }); await loadAll(); } else setError('CSV import failed. Review invalid rows and duplicates.'); }
  async function acceptMatch(id) { const res = await api(`/reconciliation/${id}/accept`, { method: 'POST' }); if (res.ok) await loadAll(); else setError('Could not accept match.'); }
  async function completeGoal(id) { const res = await api(`/goals/${id}/complete`, { method: 'POST' }); if (res.ok) { setSuccess('Goal completed.'); await loadAll(); } }
  async function dismissSuggestion(id) { const res = await api(`/intelligence/suggestions/${id}/dismiss`, { method: 'POST' }); if (res.ok) await loadAll(); }
  async function dismissInsight(id) { const res = await api(`/insights/${id}/dismiss`, { method: 'POST' }); if (res.ok) await loadAll(); else setError('Could not dismiss Insight.'); }
  async function reviewInsight(id) { const res = await api(`/insights/${id}/reviewed`, { method: 'POST' }); if (res.ok) await loadAll(); else setError('Could not mark Insight as reviewed.'); }
  async function refreshInsights() { const res = await api(`/insights/refresh?horizon_days=${rangeDays}`, { method: 'POST' }); if (res.ok) { setSuccess('Financial Insights refreshed.'); await loadAll(); } else setError('Could not refresh Financial Insights.'); }

  const quickDefaults = (type) => {
    const defaults = type === 'recurring'
      ? { account_id: '', card_id: '' }
      : { account_id: type === 'planned' ? null : data.accounts[0]?.id || '', destination_account_id: data.accounts[0]?.id || '' };
    return { type, values: normaliseRecord(type, defaults) };
  };
  const openQuickAdd = (type) => { setQuickMenuOpen(false); setQuick(quickDefaults(type)); };
  const openForecastDetail = (event) => { const source = forecastSource(event, data); setDetail({ event, ...source }); };
  const editForecastSource = () => { if (!detail?.type || !detail?.record) return; const { type, record } = detail; setDetail(null); setEdit({ type, label: recordLabels[type], row: record, values: normaliseRecord(type, record) }); };
  const navigate = (item) => { setActive(item); if (isMobile) { setMobileNavOpen(false); window.requestAnimationFrame(() => window.scrollTo({ top: 0, left: 0, behavior: 'auto' })); } };
  const closeMobileNav = (restoreFocus = true) => { setMobileNavOpen(false); if (restoreFocus) window.requestAnimationFrame(() => menuButtonRef.current?.focus({ preventScroll: true })); };

  if (!auth) return <main className="login"><div className="login-card"><img className="login-logo" src={logo} alt="Fynvo"/><p>Loading...</p></div></main>;
  if (!auth.authenticated) return <main className="login"><form className="login-card" onSubmit={submitAuth}><img className="login-logo" src={logo} alt="Fynvo"/><p>Know what's coming.</p>{auth.setup_required && <p className="notice">Create the first administrator account.</p>}<Field label="Username" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })}/>{auth.setup_required && <Field label="Display name" value={form.display_name} onChange={(e) => setForm({ ...form, display_name: e.target.value })}/>}<Field label="Password" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })}/>{error && <p className="error">{error}</p>}<button className="primary">{auth.setup_required ? 'Create account' : 'Sign in'}</button></form></main>;

  return <div className={`shell ${mobileNavOpen ? 'mobile-nav-open' : ''}`}>
    <aside className="sidebar" id="fynvo-navigation" aria-label="Fynvo navigation" aria-hidden={isMobile && !mobileNavOpen ? 'true' : undefined} inert={isMobile && !mobileNavOpen ? true : undefined}>
      <button ref={closeButtonRef} className="mobile-nav-close" type="button" aria-label="Close Fynvo navigation" onClick={() => closeMobileNav()}>×</button>
      <div className="brand"><img src={mark} alt=""/><div><strong>Fynvo</strong><small>Know what's coming.</small></div></div>
      <nav aria-label="Primary navigation">{navGroups.map((group) => <div className="nav-group" key={group.label}><small>{group.label}</small>{group.items.map((item) => <button key={item} className={active === item ? 'active' : ''} aria-current={active === item ? 'page' : undefined} onClick={() => navigate(item)}>{item}</button>)}</div>)}</nav>
      <button className="sidebar-logout" type="button" onClick={logout}>Logout</button>
      <div className="user-card"><span>{(auth.user?.display_name || 'SP').slice(0, 2).toUpperCase()}</span><div><strong>{auth.user?.display_name}</strong><small>Household</small></div></div>
    </aside>
    <button className="mobile-nav-backdrop" type="button" aria-label="Close Fynvo navigation" tabIndex={mobileNavOpen ? 0 : -1} onClick={() => closeMobileNav()}></button>
    <main className="content">
      <div className="mobile-app-bar" aria-label="Fynvo application controls"><button ref={menuButtonRef} className="mobile-menu-button" type="button" aria-label={mobileNavOpen ? 'Close Fynvo navigation' : 'Open Fynvo navigation'} aria-expanded={mobileNavOpen} aria-controls="fynvo-navigation" onClick={() => setMobileNavOpen((open) => !open)}><span aria-hidden="true">☰</span><span className="sr-only">Menu</span></button><strong className="mobile-app-identity">Fynvo</strong></div>
      <header className="header"><div><h1>{active === 'Overview' ? `${greeting}, ${auth.user?.display_name || 'there'}! 👋` : active}</h1><p>{active === 'Overview' ? "Here's your financial overview and what's ahead." : active === 'Insights' ? 'Understand what is changing, why it matters and which data supports it.' : 'Manage household financial records and planning.'}</p></div><div className="header-actions"><label className="select-shell">Date range<select value={rangeDays} onChange={(e) => setRangeDays(Number(e.target.value))}>{horizonOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><button className="primary ghost" onClick={() => setQuickMenuOpen(true)}>+ Quick Add</button></div></header>{error && <p className="error banner">{error}</p>}{success && <p className="success banner">{success}</p>}
      {active === 'Overview' && <><Overview data={data} setActive={navigate} rangeDays={rangeDays} setQuick={setQuick} quickDefaults={quickDefaults} loading={dashboardLoading}/><PaymentsAttentionV17 rows={data.paymentAttention} money={money} dateLabel={dateLabel} onRefresh={loadAll}/></>}
      {active === 'Cash Flow' && <ForecastPage forecast={data.command?.forecast?.expected || data.forecast} onView={openForecastDetail}/>} 
      {active === 'Calendar' && <CalendarPage command={data.command}/>} 
      {active === 'CSV Import' && <><CsvImport state={importState} setState={setImportState} accounts={data.accounts} previewImport={previewImport} commitImport={commitImport}/><PaymentReconciliationV17 money={money} dateLabel={dateLabel}/></>} 
      {active === 'Import History' && <ImportHistory rows={data.imports}/>} 
      {active === 'Review Queue' && <><ReviewQueue rows={data.review} acceptMatch={acceptMatch}/><PaymentReconciliationV17 money={money} dateLabel={dateLabel}/></>} 
      {active === 'Spending Intelligence' && <SpendingIntelligence suggestions={data.suggestions} dismissSuggestion={dismissSuggestion}/>} 
      {active === 'Insights' && <InsightsPage insights={data.insights} health={data.financialHealth || data.command?.financial_health} onDismiss={dismissInsight} onReviewed={reviewInsight} onNavigate={navigate} onRefresh={refreshInsights}/>} 
      {active === 'Budgeting' && <Budgeting budgets={data.budgets} analysis={data.budgetAnalysis} onEdit={(row) => setEdit({ type: 'budgets', label: 'Budget', row, values: normaliseRecord('budgets', row) })}/>} 
      {active === 'Goals' && <GoalsPage goals={data.goals} accounts={data.accounts} onEdit={(row) => setEdit({ type: 'goals', label: 'Goal', row, values: normaliseRecord('goals', row) })} onAdd={() => setQuick(quickDefaults('goals'))} onComplete={completeGoal}/>} 
      {active === 'Categories' && <CategoriesPageV0174 rangeDays={rangeDays} onEdit={setEdit} money={money}/>} 
      {active === 'Recurring Expenses' && <RecurringExpensesPageV0174 data={data} rangeDays={rangeDays} onEdit={setEdit} money={money} dateLabel={dateLabel} normaliseRecord={normaliseRecord}/>} 
      {active === 'Accounts' && <AccountsPageV14 rows={data.accounts} cards={data.cards} onEdit={setEdit} onAdd={() => setQuick(quickDefaults('accounts'))} onOpenCards={() => navigate('Cards')} money={money} normaliseRecord={normaliseRecord}/>} 
      {active === 'Cards' && <CardsPageV17 accounts={data.accounts} cards={data.cards} onRefresh={loadAll}/>} 
      {active === 'Income' && <IncomePageV14 rows={data.income} onEdit={setEdit} onAdd={() => setQuick(quickDefaults('income'))} money={money} dateLabel={dateLabel} normaliseRecord={normaliseRecord}/>} 
      {active === 'Bills' && <BillsPageV14 rows={data.bills} onEdit={setEdit} onAdd={() => setQuick(quickDefaults('bills'))} money={money} dateLabel={dateLabel} normaliseRecord={normaliseRecord}/>} 
      {active === 'Planned Spending' && <PlannedSpendingPageV14 rows={data.planned} onEdit={setEdit} onAdd={() => setQuick(quickDefaults('planned'))} money={money} dateLabel={dateLabel} normaliseRecord={normaliseRecord}/>} 
      {active === 'Transactions' && <RecordTable active={active} data={data} onEdit={setEdit}/>} 
      <footer className="app-footer">Fynvo v{APP_VERSION}</footer>
    </main>
    {edit && <EditModal edit={edit} setEdit={setEdit} onSubmit={saveEdit} data={data}/>} 
    {quick && <EditModal edit={{ ...quick, row: { id: null }, label: `New ${recordLabels[quick.type] || 'Record'}` }} setEdit={setQuick} onSubmit={(e) => { e.preventDefault(); createRecord(quick.type, quick.values); }} data={data}/>} 
    {quickMenuOpen && <QuickAddModal onClose={() => setQuickMenuOpen(false)} onChoose={openQuickAdd}/>} 
    {detail && <ForecastDetailModal detail={detail} data={data} onClose={() => setDetail(null)} onEdit={editForecastSource}/>} 
  </div>;
}

function Overview({ data, setActive, rangeDays, setQuick, quickDefaults, loading }) { const command = data.command || {}; const kpis = command.kpis || {}; const forecast = command.forecast?.baseline; const expected = command.forecast?.expected; const planned = command.top_planned_spending || data.planned || []; const attention = command.attention || {}; return <div className="dashboard-page"><section className="kpi-grid five"><Kpi icon="💵" label="Available Cash" value={kpis.available_cash} loading={loading}/><Kpi icon="📈" label="Expected Income" value={kpis.expected_income} hint={`${rangeDays} days`} loading={loading}/><Kpi icon="🧾" label="Scheduled Commitments" value={kpis.scheduled_commitments} hint={`${rangeDays} days`} loading={loading}/><Kpi icon="🛒" label="Planned Spending" value={kpis.planned_spending} hint={`${rangeDays} days`} loading={loading}/><Kpi icon="↗" label="Projected Balance" value={kpis.projected_balance} hint={`End of ${rangeDays} days`} loading={loading}/></section><section className="command-grid"><article className="panel chart-panel"><PanelHead title="Cash Flow Forecast" action="View full cash flow →" onAction={() => setActive('Cash Flow')}/><CashFlowChart baseline={forecast} expected={expected}/><ForecastMetrics forecast={forecast}/></article><article className="panel"><PanelHead title="Forecast Summary" meta={`End of ${rangeDays} days`}/><SummaryRow label="Baseline Forecast" value={command.forecast?.summary?.baseline}/><SummaryRow label="Expected Forecast" value={command.forecast?.summary?.expected}/>{command.forecast?.summary?.lowest_balance && <SummaryRow label="Lowest Balance" value={command.forecast.summary.lowest_balance.balance}/>}<button className="link-button" onClick={() => setActive('Cash Flow')}>View cash flow →</button></article><article className="panel"><PanelHead title="Upcoming Commitments" action="View calendar →" onAction={() => setActive('Calendar')}/><CompactEvents rows={command.upcoming_commitments || []}/></article></section><section className="card-grid"><article className="panel"><PanelHead title="Upcoming" meta="Next 7 days" action="View all →" onAction={() => setActive('Calendar')}/><CompactEvents rows={(command.upcoming || []).slice(0, 4)}/></article><article className="panel"><PanelHead title="Top Planned Spending" action="+ Quick Add" onAction={() => setQuick(quickDefaults('planned'))}/>{planned.length ? planned.slice(0, 4).map((item) => <div className="list-row" key={item.id || item.name}><span>{item.name}<small>{dateLabel(item.planned_date)}</small></span><strong>{money(item.estimated_amount) || 'Loading…'}</strong></div>) : <Empty title="No planned spending">No planned purchases during this period.</Empty>}</article><article className="panel attention"><PanelHead title="Financial Health" action="View insights →" onAction={() => setActive('Insights')}/><strong>{attention.headline || 'No major issues detected'}</strong></article></section></div>; }
function Kpi({ icon, label, value, hint, loading = false }) { const formatted = money(value); return <article className={`kpi ${loading ? 'is-loading' : ''}`}><span className="kpi-icon">{icon}</span><div><span>{label}</span><strong className={!loading && value !== null && value !== undefined ? amountClass(value) : ''}>{loading || formatted === null ? <span className="loading-value">Loading…</span> : formatted}</strong>{hint && <small>{hint}</small>}</div></article>; }
function PanelHead({ title, meta, action, onAction }) { return <div className="panel-head compact"><div><h2>{title}</h2>{meta && <small>{meta}</small>}</div>{action && <button className="link-button" onClick={onAction}>{action}</button>}</div>; }
function SummaryRow({ label, value }) { const formatted = money(value); return <div className="summary-row"><span>{label}</span><strong className={value !== null && value !== undefined ? amountClass(value) : ''}>{formatted || 'Loading…'}</strong></div>; }
function CashFlowChart({ baseline, expected }) { return <CashFlowChartV0174 baseline={baseline} expected={expected} money={money} dateLabel={dateLabel} Empty={Empty}/>; }
function ForecastMetrics({ forecast }) { if (!forecast) return null; return <div className="metric-strip"><div><span>End of period</span><strong>{money(forecast.final_balance) || 'Loading…'}</strong></div><div><span>Lowest Balance</span><strong className="negative">{money(forecast.lowest_balance?.balance) || 'Loading…'}</strong><small>{dateLabel(forecast.lowest_balance?.date)}</small></div>{forecast.shortfall ? <div className="risk"><span>Cash shortfall risk</span><strong>{money(forecast.shortfall.balance) || 'Loading…'}</strong><small>{dateLabel(forecast.shortfall.date)}</small></div> : <div className="safe"><span>No forecast shortfall</span><strong>Clear</strong><small>Based on current records</small></div>}</div>; }
function CompactEvents({ rows }) { return rows?.length ? rows.slice(0, 6).map((row, index) => <div className="event-row" key={`${row.date}-${row.name}-${index}`}><time>{dateLabel(row.date).slice(0, 6)}</time><span>{row.name}<small>{row.category || row.source_type || row.source}</small></span><strong className={amountClass(row.amount)}>{money(row.amount) || 'Loading…'}</strong></div>) : <Empty title="Nothing scheduled">No matching financial events in this period.</Empty>; }
function GoalsPage({ goals, onEdit, onAdd }) { const totals = goals.reduce((acc, goal) => { acc.target += parseAmount(goal.target_amount); acc.current += parseAmount(goal.progress?.current || goal.current_amount); if (goal.progress?.status === 'on_track' || goal.progress?.status === 'ahead') acc.onTrack += 1; return acc; }, { target: 0, current: 0, onTrack: 0 }); return <section className="stack"><div className="kpi-grid four"><Kpi icon="🎯" label="Active Goals" value={goals.length}/><Kpi icon="🏁" label="Total Target" value={totals.target}/><Kpi icon="💰" label="Allocated / Saved" value={totals.current}/><Kpi icon="✅" label="Goals On Track" value={`${totals.onTrack} of ${goals.length}`}/></div><article className="panel"><PanelHead title="Financial Goals" action="+ Add Goal" onAction={onAdd}/>{goals.map((goal) => <div className="list-row" key={goal.id}><span>{goal.name}</span><button onClick={() => onEdit(goal)}>Edit</button></div>)}</article></section>; }
function ForecastPage({ forecast, onView }) { const events = forecast?.events || []; return <section className="panel"><PanelHead title="Cash Flow"/><CashFlowChart baseline={forecast} expected={forecast}/><ForecastMetrics forecast={forecast}/><div className="cashflow-events"><h2>Upcoming cash flow</h2>{events.length ? <div className="table cashflow-table">{events.map((item, i) => <div className="tr" key={`${item.source_type}-${item.source_id || i}-${item.date}`}><span>{dateLabel(item.date)}</span><span className="event-name">{item.name}<small>{item.category || item.source_type?.replaceAll('_', ' ')}</small></span><span className={amountClass(item.amount)}>{money(item.amount) || 'Loading…'}</span><span>{money(item.forecast_balance) || 'Loading…'}</span><button type="button" className="event-action" onClick={() => onView(item)}>View more info</button></div>)}</div> : <Empty title="Nothing scheduled">No matching financial events in this period.</Empty>}</div></section>; }
function CalendarPage({ command }) { return <section className="panel"><PanelHead title="Financial Calendar"/><CompactEvents rows={command?.upcoming || []}/></section>; }
function SpendingIntelligence({ suggestions, dismissSuggestion }) { return <section className="panel"><PanelHead title="Spending Intelligence"/>{suggestions?.length ? suggestions.map((item) => <div className="suggestion" key={item.id}><div><strong>{item.title || item.suggestion_type}</strong></div><Badge>{item.confidence || 'review'}</Badge><button onClick={() => dismissSuggestion(item.id)}>Dismiss</button></div>) : <Empty title="No suggestions waiting">Spending Intelligence has no unresolved items.</Empty>}</section>; }
function RecordTable({ active, data, onEdit }) { const cfg = { Accounts: ['accounts', data.accounts, 'Account'], Transactions: ['transactions', data.transactions, 'Transaction'], Income: ['income', data.income, 'Income'], Bills: ['bills', data.bills, 'Bill'], 'Planned Spending': ['planned', data.planned, 'Planned Spending'] }[active]; const [type, rows, label] = cfg; return <section className="panel"><div className="panel-head"><div><h2>{active}</h2></div><button className="primary ghost" onClick={() => onEdit({ type, label: `New ${label}`, row: { id: null }, values: normaliseRecord(type, {}) })}>+ Add</button></div>{rows.length ? <div className="table">{rows.map((row) => <div className="tr" key={row.id}><span>{dateLabel(row.date || row.transaction_date || row.due_date || row.next_payment_date || row.planned_date)}</span><span>{row.name || row.description || row.merchant || row.account_type}</span><span>{money(row.amount || row.estimated_amount || row.current_balance) || ''}</span><span>{active === 'Accounts' ? accountTypeLabel(row.account_type) : row.status || row.completeness || 'Active'}</span><button onClick={() => onEdit({ type, label, row, values: normaliseRecord(type, row) })}>Edit</button></div>)}</div> : <Empty title={`No ${active.toLowerCase()} yet`}>Use Add to create the first record.</Empty>}</section>; }
function Budgeting({ budgets, analysis, onEdit }) { return <section className="panel"><PanelHead title="Budgeting"/><SummaryRow label="Base budget" value={analysis?.summary?.base_budget}/><SummaryRow label="Actual spending" value={analysis?.summary?.actual}/>{budgets.map((row) => <div className="list-row" key={row.id}><span>{row.name}</span><button onClick={() => onEdit(row)}>Edit</button></div>)}</section>; }
function CsvImport({ state, setState, accounts, previewImport, commitImport }) { return <section className="panel"><PanelHead title="CSV Import & Reconciliation"/><form className="form-grid" onSubmit={previewImport}><Field label="Filename" value={state.filename} onChange={(e) => setState({ ...state, filename: e.target.value })}/><Field label="Account"><select value={state.account_id} onChange={(e) => setState({ ...state, account_id: e.target.value })}><option value="">Choose account</option>{accounts.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><label className="field wide"><span>CSV text</span><textarea rows="10" value={state.csv_text} onChange={(e) => setState({ ...state, csv_text: e.target.value })}/></label><button className="primary">Preview CSV</button></form>{state.preview && <button className="primary" onClick={commitImport}>Commit Import</button>}</section>; }
function ImportHistory({ rows }) { return <section className="panel"><PanelHead title="Import History"/>{rows?.length ? rows.map((row) => <div className="list-row" key={row.id}><span>{row.filename}</span><strong>{row.imported_count} imported</strong></div>) : <Empty title="No imports yet">Import a CSV to see history.</Empty>}</section>; }
function ReviewQueue({ rows, acceptMatch }) { return <section className="panel"><PanelHead title="Reconciliation Review Queue"/>{rows?.length ? rows.map((row) => <div className="suggestion" key={row.id}><div><strong>{row.source_type}</strong></div><button onClick={() => acceptMatch(row.id)}>Accept</button></div>) : <Empty title="No reconciliation items">Imported transactions that need review will appear here.</Empty>}</section>; }
function QuickAddModal({ onClose, onChoose }) { return <div className="modal-backdrop"><section className="modal"><div className="panel-head"><h2>Quick Add</h2><button type="button" onClick={onClose}>×</button></div><div className="quick-add-grid">{quickAddOptions.map(([type, label, description]) => <button type="button" className="quick-add-choice" key={type} onClick={() => onChoose(type)}><strong>{label}</strong><small>{description}</small></button>)}</div></section></div>; }
function ForecastDetailModal({ detail, onClose, onEdit }) { const event = detail.event || {}; const record = detail.record || {}; return <div className="modal-backdrop"><section className="modal detail-modal"><div className="panel-head"><div><h2>{event.name || 'Cash flow item'}</h2></div><button onClick={onClose}>×</button></div><div className="detail-grid"><div className="detail-item"><span>Date</span><strong>{dateLabel(event.date)}</strong></div><div className="detail-item"><span>Amount</span><strong>{money(event.amount)}</strong></div><div className="detail-item"><span>Category</span><strong>{event.category || record.category || 'Not set'}</strong></div></div><div className="modal-actions"><button onClick={onClose}>Close</button>{detail.record && <button className="primary" onClick={onEdit}>Edit source</button>}</div></section></div>; }
function EditModal({ edit, setEdit, onSubmit, data }) { const values = edit.values || {}; const set = (key, value) => setEdit({ ...edit, values: { ...values, [key]: value } }); return <div className="modal-backdrop"><form className="modal" onSubmit={onSubmit}><div className="panel-head"><h2>{edit.label}</h2><button type="button" onClick={() => setEdit(null)}>×</button></div><DynamicFields type={edit.type} values={values} set={set} data={data} currentId={edit.row?.id}/><div className="modal-actions"><button type="button" onClick={() => setEdit(null)}>Cancel</button><button className="primary">Save</button></div></form></div>; }
function DynamicFields({ type, values, set, data, currentId }) {
  const accountSelect = (key) => <select value={values[key] || ''} onChange={(e) => set(key, e.target.value)}><option value="">Choose account</option>{data.accounts.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select>;
  const text = (key, label, inputType = 'text', required = false, className = '') => <Field label={label} className={className}><input type={inputType} required={required} value={values[key] ?? ''} onChange={(e) => set(key, e.target.value)}/></Field>;
  if (type === 'transactions') return <div className="form-grid">{text('date', 'Date', 'date', true)}{text('amount', 'Amount', 'text', true)}{text('description', 'Description', 'text', true)}<Field label="Account">{accountSelect('account_id')}</Field>{text('merchant', 'Merchant')}{text('category', 'Category')}</div>;
  if (type === 'income') return <div className="form-grid">{text('name', 'Name', 'text', true)}{text('amount', 'Amount')}{text('next_payment_date', 'Next payment', 'date')}<Field label="Frequency"><select value={values.frequency} onChange={(e) => set('frequency', e.target.value)}><option>weekly</option><option>fortnightly</option><option>monthly</option><option>quarterly</option><option value="yearly">annual</option></select></Field><Field label="Destination account">{accountSelect('destination_account_id')}</Field>{text('payer', 'Payer')}{text('category', 'Category')}</div>;
  if (type === 'recurring') return <div className="form-grid recurring-v17-form">{text('name', 'Name', 'text', true)}{text('amount', 'Amount')}{text('next_due_date', 'Next due', 'date')}<Field label="Frequency"><select value={values.frequency} onChange={(e) => set('frequency', e.target.value)}><option>weekly</option><option>fortnightly</option><option>every_4_weeks</option><option>monthly</option><option>quarterly</option><option>yearly</option></select></Field><Field label="Category"><CategorySelect categories={data.categories} value={values.category || ''} onChange={(e) => set('category', e.target.value)}/></Field>{text('expense_type', 'Expense type')}{text('payee_merchant', 'Payee / merchant')}<Field label="Amount type"><select value={values.amount_type || 'fixed'} onChange={(e) => set('amount_type', e.target.value)}><option value="fixed">Fixed Amount</option><option value="variable_estimated">Variable / Estimated</option></select></Field><RecurringPaymentFieldsV17 values={values} set={set} data={data}/>{text('notes', 'Notes', 'text', false, 'wide')}</div>;
  if (type === 'bills') return <div className="form-grid">{text('name', 'Name', 'text', true)}{text('amount', 'Amount')}{text('due_date', 'Due date', 'date')}{text('provider', 'Provider')}{text('bill_type', 'Bill type')}<Field label="Account">{accountSelect('account_id')}</Field></div>;
  if (type === 'planned') return <div className="form-grid planned-form">{text('name', 'Name', 'text', true, 'wide')}<div className="planned-primary-row">{text('estimated_amount', 'Estimated amount')}{text('planned_date', 'Planned date', 'date')}</div><Field label="Category"><CategorySelect categories={data.categories} value={values.category || ''} onChange={(e) => set('category', e.target.value)}/></Field><Field label="Status"><select value={values.status} onChange={(e) => set('status', e.target.value)}><option value="wishlist">Wishlist</option><option value="planned">Planned</option><option value="committed">Committed</option><option value="purchased">Purchased</option><option value="cancelled">Cancelled</option></select></Field>{text('description', 'Description', 'text', false, 'wide')}{text('notes', 'Notes', 'text', false, 'wide')}</div>;
  if (type === 'categories') return <div className="form-grid">{text('name', 'Name', 'text', true)}<Field label="Parent category"><select value={values.parent_id || ''} onChange={(e) => set('parent_id', e.target.value)}><option value="">None (parent category)</option>{(data.categories || []).filter((row) => row.parent_id == null && Number(row.id) !== Number(currentId)).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><Field label="Type"><select value={values.category_type} onChange={(e) => set('category_type', e.target.value)}><option>expense</option><option>income</option><option>transfer</option></select></Field>{text('notes', 'Notes')}</div>;
  if (type === 'accounts') return <div className="form-grid">{text('name', 'Account name', 'text', true)}{text('opening_balance', 'Opening balance', 'text', true)}<Field label="Account type"><select value={values.account_type} onChange={(e) => set('account_type', e.target.value)}>{accountTypeOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>{text('institution', 'Institution')}</div>;
  if (type === 'budgets') return <div className="form-grid">{text('name', 'Name', 'text', true)}{text('amount', 'Amount')}{text('start_date', 'Start date', 'date')}{text('category_name', 'Category')}{text('notes', 'Notes')}</div>;
  if (type === 'goals') return <div className="form-grid">{text('name', 'Name', 'text', true)}{text('target_amount', 'Target amount')}{text('current_amount', 'Current amount')}{text('target_date', 'Target date', 'date')}{text('notes', 'Notes')}</div>;
  return <div className="form-grid">{Object.keys(values).map((key) => text(key, key))}</div>;
}
