import ReactDOM from 'react-dom/client';
import App from './AppV13.jsx';
import './auth-v15.css';
import './font-v13.css';
import './styles.css';
import './mobile-v16.css';
import './hardening-v17.css';
import './ux-v171.css';
import './corrective-v0175.css';
import './v018.css';
import './household-v12.css';
import './v13-cashflow.css';
import './v14.css';
import './v142.css';
import './v143.css';
import './recurring-v151.css';
import './payment-v17.css';
import './v191.css';
import './v111.css';
import './corrective-v1161.css';
import './corrective-v1162.css';
import './accounts-cards-v1163.css';
import './startup-v1172.css';

ReactDOM.createRoot(document.getElementById('root')).render(<App />);
