"""Canonical dated cash effects shared by forecasting and payment decisions."""

from __future__ import annotations

import hashlib
import json
from collections import defaultdict
from datetime import timedelta

from sqlalchemy import text

from .balance_evidence import eligible_balances
from .money import cents_to_decimal, parse_money

RULES_VERSION = "cash-flow-1"


def input_fingerprint(db, user):
    """Hash financial inputs across scopes, without timestamps generated by reads."""
    connection = db.connection().connection.driver_connection
    cache_key = (user.id, db.get_transaction(), connection.total_changes)
    cache = db.info.setdefault("financial_input_fingerprints", {})
    if cache_key in cache:
        return cache[cache_key]
    tables = (
        "accounts",
        "cards",
        "categories",
        "transactions",
        "income_sources",
        "recurring_expenses",
        "scheduled_payments",
        "bills",
        "planned_spending",
        "transfers",
        "effective_amount_changes",
        "forecast_occurrence_overrides",
        "balance_observations",
        "reconciliation_links",
    )
    inputs = {
        table: [
            dict(row)
            for row in db.execute(
                text(f"SELECT * FROM {table} WHERE user_id=:uid ORDER BY id"),
                {"uid": user.id},
            ).mappings()
        ]
        for table in tables
    }
    inputs["buffer"] = db.execute(
        text("SELECT value FROM app_config WHERE key=:key"),
        {"key": f"safe_to_spend.buffer.{user.id}"},
    ).scalar()
    result = hashlib.sha256(
        json.dumps(inputs, sort_keys=True, default=str).encode()
    ).hexdigest()
    cache[cache_key] = result
    return result


def settled_income_keys(db, user):
    """Use the same accepted receipt identities in projections and pay-cycle boundaries."""
    from . import payment_planning as planning

    issues = []
    receipts = (
        db.execute(
            text(
                "SELECT rl.source_id,t.transaction_date FROM reconciliation_links rl JOIN transactions t ON t.id=rl.transaction_id AND t.user_id=rl.user_id WHERE rl.user_id=:uid AND rl.source_type='income' AND rl.status='matched' AND t.status NOT IN ('pending','cancelled','duplicate') AND t.amount_cents>0"
            ),
            {"uid": user.id},
        )
        .mappings()
        .all()
    )
    settled_keys = set()
    for receipt in receipts:
        from datetime import date

        received = date.fromisoformat(str(receipt["transaction_date"])[:10])
        candidates = [
            income
            for income in planning._income_events(
                db, user, received - timedelta(days=7), received + timedelta(days=7)
            )
            if income["income_id"] == receipt["source_id"]
        ]
        if candidates:
            distances = [
                (
                    abs((date.fromisoformat(income["date"]) - received).days),
                    income["date"],
                )
                for income in candidates
            ]
            nearest = min(distance for distance, _ in distances)
            matches = [when for distance, when in distances if distance == nearest]
            if len(matches) == 1:
                settled_keys.add(f"income:{receipt['source_id']}:{matches[0]}")
            else:
                issues.append(
                    {
                        "code": "ambiguous_income_receipt",
                        "source_id": receipt["source_id"],
                    }
                )
    return settled_keys, issues


def canonical_events(db, user, start, end, mode="baseline", scenario=None):
    from . import forecast, payments_v114, v13_cashflow
    from . import payment_planning as planning
    from .finance import today_local

    anchor = min(start, today_local())
    payments_v114.ensure_scheduled_payments(
        db,
        user,
        horizon_days=max(370 + (today_local() - anchor).days, (end - anchor).days + 2),
        today=anchor,
    )
    # Python's SQLite driver does not start a read transaction for SELECT.
    # Pin the input snapshot only after occurrence materialization has committed.
    raw_connection = db.connection().connection.driver_connection
    if not raw_connection.in_transaction:
        db.execute(text("BEGIN"))
    scheduled = {
        int(row["id"]): dict(row)
        for row in db.execute(
            text("SELECT * FROM scheduled_payments WHERE user_id=:uid"),
            {"uid": user.id},
        ).mappings()
    }
    events, issues = [], []
    for row in db.execute(
        text(
            "SELECT id FROM recurring_expenses WHERE user_id=:uid AND is_active=1 AND (end_date IS NULL OR end_date>=:anchor) AND (next_due_date IS NULL OR amount_cents IS NULL)"
        ),
        {"uid": user.id, "anchor": anchor},
    ).mappings():
        issues.append(
            {
                "code": "incomplete_obligation",
                "source_type": "recurring_expense",
                "source_id": row["id"],
            }
        )
    for row in db.execute(
        text(
            "SELECT id FROM planned_spending WHERE user_id=:uid AND archived_at IS NULL AND include_in_forecast=1 AND status IN ('planned','committed') AND (planned_date IS NULL OR estimated_amount_cents IS NULL)"
        ),
        {"uid": user.id},
    ).mappings():
        issues.append(
            {
                "code": "incomplete_obligation",
                "source_type": "planned_spending",
                "source_id": row["id"],
            }
        )
    for income in planning._income_events(db, user, anchor, end):
        events.append(
            {
                "date": income["date"],
                "occurrence_date": income["date"],
                "name": income["name"],
                "amount_cents": income["amount_cents"],
                "amount": income["amount"],
                "direction": "income",
                "source_type": "income",
                "source_id": income["income_id"],
                "account_id": income["account_id"],
                "confidence": "confirmed",
                "estimated": False,
                "financial_layer": "committed",
                "category": "Income",
                "event_key": f"income:{income['income_id']}:{income['date']}",
                "explanation": "Scheduled income",
            }
        )
    for event in events:
        amount = (scenario or {}).get("amount_changes", {}).get(event["event_key"])
        if amount is not None:
            event.update(amount_cents=int(amount), amount=cents_to_decimal(int(amount)))
    settled_keys, receipt_issues = settled_income_keys(db, user)
    issues.extend(receipt_issues)
    events = [e for e in events if e["event_key"] not in settled_keys]
    removed = set((scenario or {}).get("remove_recurring_ids", []))
    payment_rows = planning.canonical_payment_rows(db, user)
    bill_groups = defaultdict(list)
    for row in payment_rows:
        if (
            row["source_type"] == "bill"
            and row.get("scheduled_payment_id")
            and row["status"] != "cancelled"
        ):
            bill_groups[row["scheduled_payment_id"]].append(row)
    ignored_bills = set()
    for sid, group in bill_groups.items():
        if len(group) > 1:
            issues.append(
                {
                    "code": "ambiguous_bill_link",
                    "scheduled_payment_id": sid,
                    "bill_ids": [r["id"] for r in group],
                }
            )
            conservative = max(
                group,
                key=lambda r: (
                    planning._amount_cents(r)
                    if r["status"] in planning.FUNDING_STATUSES
                    else 0,
                    r["id"],
                ),
            )
            ignored_bills.update(
                r["id"] for r in group if r["id"] != conservative["id"]
            )
    for row in payment_rows:
        if row["source_type"] == "bill" and row["id"] in ignored_bills:
            continue
        if row.get("status") not in planning.FUNDING_STATUSES:
            continue
        if row.get("identity_warning"):
            issues.append({"code": "ambiguous_occurrence", "source_id": row["id"]})
        raw = (
            scheduled.get(int(row["id"]))
            if row["source_type"] == "scheduled_payment"
            else None
        )
        original = (
            str(raw["occurrence_date"] or raw["expected_date"])[:10]
            if raw
            else row.get("due_date")
        )
        when = planning._as_date(row.get("expected_date") or row.get("due_date"))
        if when is None or (
            row.get("amount")
            if row["source_type"] == "bill"
            else row.get("expected_amount")
        ) in (None, ""):
            issues.append(
                {
                    "code": "incomplete_obligation",
                    "source_type": row["source_type"],
                    "source_id": row["id"],
                }
            )
            continue
        if (
            row["source_type"] == "scheduled_payment"
            and row.get("recurring_expense_id") in removed
        ):
            continue
        amount = planning._amount_cents(row)
        source_type = "recurring_expense" if raw else "bill"
        source_id = row["recurring_expense_id"] if raw else row["id"]
        if raw:
            amount, _ = forecast.amount_at(
                db, user, "recurring_expense", source_id, amount, when
            )
        changes = (scenario or {}).get("amount_changes", {})
        amount = changes.get(
            f"{source_type}:{source_id}:{original}",
            changes.get(f"{source_type}:{source_id}:{when.isoformat()}", amount),
        )
        account_id = planning._derived_account_id(row, db, user)
        estimated = bool(
            raw
            and db.execute(
                text(
                    "SELECT variable_amount FROM recurring_expenses WHERE id=:id AND user_id=:uid"
                ),
                {"id": source_id, "uid": user.id},
            ).scalar()
        )
        estimated = estimated or any(
            label in str(row.get("original_status") or "").lower()
            for label in ("estimated", "expected")
        )
        events.append(
            {
                "date": max(when, anchor).isoformat(),
                "original_due_date": when.isoformat(),
                "occurrence_date": original,
                "name": row["name"],
                "amount_cents": -abs(int(amount)),
                "amount": cents_to_decimal(-abs(int(amount))),
                "direction": "expense",
                "source_type": source_type,
                "source_id": source_id,
                "scheduled_payment_id": raw["id"]
                if raw
                else row.get("scheduled_payment_id"),
                "account_id": account_id,
                "status": row["status"],
                "occurrence_status": "overdue" if when < anchor else row["status"],
                "confidence": "estimated" if estimated else "confirmed",
                "estimated": estimated,
                "financial_layer": "committed",
                "category": row.get("category") or "Uncategorised",
                "event_key": f"payment:{raw['id']}" if raw else f"bill:{row['id']}",
                "explanation": "Remaining canonical obligation",
            }
        )
    events += forecast._planned_events(db, user, anchor, end)
    for row in events:
        row.setdefault(
            "event_key", f"{row['source_type']}:{row.get('source_id')}:{row['date']}"
        )
    # Future ledger entries are intentions, not money already spent today.
    for row in db.execute(
        text(
            "SELECT * FROM transactions WHERE user_id=:uid AND transaction_date>:today AND transaction_date<=:end AND transfer_id IS NULL AND status NOT IN ('pending','cancelled','duplicate')"
        ),
        {
            "uid": user.id,
            "today": min(today_local(), start - timedelta(days=1))
            if start < today_local()
            else today_local(),
            "end": end,
        },
    ).mappings():
        amount = int(row["amount_cents"])
        events.append(
            {
                "date": str(row["transaction_date"])[:10],
                "name": row["description"],
                "amount_cents": amount,
                "amount": cents_to_decimal(amount),
                "direction": "income" if amount >= 0 else "expense",
                "source_type": "transaction",
                "source_id": row["id"],
                "account_id": row["account_id"],
                "event_key": f"transaction:{row['id']}",
                "category": row["category"],
                "confidence": "confirmed",
                "estimated": False,
                "financial_layer": "planned",
                "explanation": "Future dated ledger entry",
            }
        )
    events += v13_cashflow._future_transfers(
        db,
        user,
        anchor
        if start < today_local()
        else max(anchor, today_local() + timedelta(days=1)),
        end,
    )
    for event in events:
        event.setdefault(
            "event_key",
            f"{event['source_type']}:{event.get('source_id')}:{event['date']}",
        )
    events = v13_cashflow._apply_overrides(events, v13_cashflow._overrides(db, user))
    if mode == "expected":
        # Residual estimates are calculated per category and week, not globally suppressed.
        rates = forecast.historical_run_rates(
            db, user, forecast_start=anchor, include_known=True
        )
        for rate in rates:
            when = anchor
            while when <= end:
                until = min(end, when + timedelta(days=6))
                known = sum(
                    -event["amount_cents"]
                    for event in events
                    if event["direction"] == "expense"
                    and event.get("category") == rate["category"]
                    and when.isoformat() <= event["date"] <= until.isoformat()
                )
                amount = max(0, int(rate["weekly_amount_cents"]) - known)
                if amount:
                    events.append(
                        forecast._event(
                            when,
                            f"Estimated {rate['category']}",
                            amount,
                            "expense",
                            "run_rate_estimate",
                            None,
                            rate["category"],
                            None,
                            "estimated",
                            "forecast",
                            "Residual historical weekly estimate",
                            True,
                        )
                    )
                when += timedelta(days=7)
    events = forecast._apply_scenario(events, scenario, anchor, end)
    for event in events:
        event.setdefault(
            "event_key",
            f"{event['source_type']}:{event.get('source_id')}:{event['date']}:{event.get('category')}",
        )
    return events, issues


def project_events(
    events, balances, account_meta, start, end, issues=None, household_offset=0
):
    running = dict(balances)
    household = sum(running.values()) + household_offset
    unassigned = household_offset
    lowest = {
        "date": start.isoformat(),
        "balance_cents": household,
        "balance": cents_to_decimal(household),
    }
    accounts = {
        aid: {
            "account_id": aid,
            "account_name": account_meta[aid].get("name"),
            "starting_balance": cents_to_decimal(value),
            "lowest_balance_cents": value,
            "lowest_balance_date": start.isoformat(),
            "first_negative_date": start.isoformat() if value < 0 else None,
            "first_buffer_breach": start.isoformat()
            if value < int(account_meta[aid].get("minimum_balance_cents") or 0)
            else None,
            "preferred_buffer": cents_to_decimal(
                int(account_meta[aid].get("minimum_balance_cents") or 0)
            ),
            "chart_points": [
                {"date": start.isoformat(), "balance": cents_to_decimal(value)}
            ],
        }
        for aid, value in running.items()
    }
    warnings, timeline = [], []
    shortfall = {**lowest, "nearby_events": []} if household < 0 else None
    seen = set()
    for event in sorted(
        events,
        key=lambda e: (
            e["date"],
            {"income": 0, "transfer": 1}.get(e["direction"], 2),
            e["event_key"],
        ),
    ):
        if (
            not start.isoformat() <= event["date"] <= end.isoformat()
            or event["event_key"] in seen
        ):
            continue
        seen.add(event["event_key"])
        row = dict(event)
        delta = int(row["amount_cents"])
        if row["direction"] == "transfer":
            amount = int(row["transfer_amount_cents"])
            from_id, to_id = int(row["from_account_id"]), int(row["to_account_id"])
            delta = (amount if to_id in running else 0) - (
                amount if from_id in running else 0
            )
            if from_id in running:
                if running[from_id] < amount:
                    warnings.append(
                        {
                            "kind": "unfunded_transfer",
                            "account_id": from_id,
                            "date": row["date"],
                            "cause": row["name"],
                        }
                    )
                running[from_id] -= amount
            if to_id in running:
                running[to_id] += amount
        elif row.get("account_id") in running:
            running[row["account_id"]] += delta
        elif row.get("account_id") in account_meta:
            delta = 0
            warnings.append(
                {
                    "kind": "excluded_funding_account",
                    "account_id": row["account_id"],
                    "date": row["date"],
                    "cause": row["name"],
                }
            )
        else:
            unassigned += delta
        household += delta
        row.update(
            forecast_balance_cents=household,
            forecast_balance=cents_to_decimal(household),
            account_balances={str(a): cents_to_decimal(v) for a, v in running.items()},
            household_amount_cents=delta,
        )
        timeline.append(row)
        if household < lowest["balance_cents"]:
            lowest = {
                "date": row["date"],
                "balance_cents": household,
                "balance": cents_to_decimal(household),
                "source": row["name"],
            }
        if household < 0 and shortfall is None:
            shortfall = {
                "date": row["date"],
                "balance_cents": household,
                "balance": cents_to_decimal(household),
                "nearby_events": timeline[-5:],
            }
        for aid, value in running.items():
            account = accounts[aid]
            account["chart_points"].append(
                {"date": row["date"], "balance": cents_to_decimal(value)}
            )
            if value < account["lowest_balance_cents"]:
                account.update(
                    lowest_balance_cents=value, lowest_balance_date=row["date"]
                )
            if value < 0 and account["first_negative_date"] is None:
                account["first_negative_date"] = row["date"]
            if (
                value < parse_money(account["preferred_buffer"])
                and account["first_buffer_breach"] is None
            ):
                account["first_buffer_breach"] = row["date"]
    for aid, account in accounts.items():
        movements = [
            event
            for event in timeline
            if event.get("account_id") == aid and event["direction"] != "transfer"
        ]
        account.update(
            income_total=cents_to_decimal(
                sum(e["amount_cents"] for e in movements if e["direction"] == "income")
            ),
            expense_total=cents_to_decimal(
                -sum(
                    e["amount_cents"] for e in movements if e["direction"] == "expense"
                )
            ),
            net_movement=cents_to_decimal(running[aid] - balances[aid]),
        )
        account.update(
            final_balance=cents_to_decimal(running[aid]),
            lowest_balance=cents_to_decimal(account["lowest_balance_cents"]),
            funding_shortfall=cents_to_decimal(
                max(
                    0,
                    parse_money(account["preferred_buffer"])
                    - account["lowest_balance_cents"],
                )
            ),
        )
        if account["first_buffer_breach"]:
            warnings.append(
                {
                    "kind": "low_balance",
                    "account_id": aid,
                    "account_name": account["account_name"],
                    "date": account["first_buffer_breach"],
                    "projected_balance": account["lowest_balance"],
                    "safety_buffer": account["preferred_buffer"],
                    "shortfall": account["funding_shortfall"],
                    "cause": "Dated obligations",
                }
            )
        if account["first_negative_date"]:
            warnings.append(
                {
                    "kind": "negative_balance",
                    "account_id": aid,
                    "account_name": account["account_name"],
                    "date": account["first_negative_date"],
                    "projected_balance": account["lowest_balance"],
                    "required_to_avoid": cents_to_decimal(
                        max(0, -account["lowest_balance_cents"])
                    ),
                    "cause": "Dated obligations",
                }
            )
    return {
        "events": timeline,
        "accounts": list(accounts.values()),
        "account_final_balances": {
            str(a): cents_to_decimal(v) for a, v in running.items()
        },
        "final_balance": cents_to_decimal(household),
        "lowest_balance": lowest,
        "shortfall": shortfall,
        "warnings": warnings,
        "unassigned_net_movement": cents_to_decimal(unassigned),
        "issues": issues or [],
        "reconciles": household == sum(running.values()) + unassigned,
    }


def projection(db, user, start, end, mode="baseline", scenario=None):
    from .finance import today_local

    actual_day = today_local()
    anchor = min(actual_day, start)
    events, issues = canonical_events(db, user, anchor, end, mode, scenario)
    evidence = eligible_balances(db, user)
    meta = {
        int(row["id"]): dict(row)
        for row in db.execute(
            text(
                "SELECT id,name,minimum_balance_cents FROM accounts WHERE user_id=:uid"
            ),
            {"uid": user.id},
        ).mappings()
    }
    balances = {a: r["current_cents"] for a, r in evidence.items()}
    if start < actual_day:
        for row in db.execute(
            text(
                "SELECT account_id,SUM(amount_cents) AS amount FROM transactions WHERE user_id=:uid AND transaction_date>=:start AND transaction_date<=:today AND status NOT IN ('pending','cancelled','duplicate') GROUP BY account_id"
            ),
            {"uid": user.id, "start": start, "today": actual_day},
        ).mappings():
            if row["account_id"] in balances:
                balances[row["account_id"]] -= int(row["amount"])
    household_offset = 0
    if start > actual_day:
        roll = project_events(
            events, balances, meta, actual_day, start - timedelta(days=1)
        )
        balances = {
            int(a): parse_money(v) for a, v in roll["account_final_balances"].items()
        }
        # Household-only events still affect the forecast but cannot be assigned fictitiously.
        household_offset = parse_money(roll["unassigned_net_movement"])
        if household_offset:
            issues.append({"code": "unassigned_roll_forward"})
    result = project_events(
        events, balances, meta, start, end, issues, household_offset
    )
    starting = sum(balances.values()) + household_offset
    totals = defaultdict(int)
    for event in result["events"]:
        totals[event["source_type"]] += event["household_amount_cents"]
    fingerprint = hashlib.sha256(
        json.dumps(
            {
                "balances": evidence,
                "events": events,
                "rules": RULES_VERSION,
                "start": str(start),
                "end": str(end),
            },
            sort_keys=True,
            default=str,
        ).encode()
    ).hexdigest()
    result.update(
        start_date=start.isoformat(),
        end_date=end.isoformat(),
        as_of=actual_day.isoformat(),
        rules_version=RULES_VERSION,
        input_fingerprint=input_fingerprint(db, user),
        projection_fingerprint=fingerprint,
        starting_balance=cents_to_decimal(starting),
        net_movement=cents_to_decimal(parse_money(result["final_balance"]) - starting),
        income_total=cents_to_decimal(
            sum(
                e["amount_cents"]
                for e in result["events"]
                if e["direction"] == "income"
            )
        ),
        expense_total=cents_to_decimal(
            -sum(
                e["amount_cents"]
                for e in result["events"]
                if e["direction"] == "expense"
            )
        ),
        account_starting_balances={
            str(a): cents_to_decimal(v) for a, v in balances.items()
        },
        balance_evidence={str(a): r for a, r in evidence.items()},
        totals_by_source={a: cents_to_decimal(v) for a, v in totals.items()},
        chart_points=[
            {
                "date": start.isoformat(),
                "balance": cents_to_decimal(starting),
                "balance_cents": starting,
                "kind": "actual",
            }
        ]
        + [
            {
                "date": e["date"],
                "balance": e["forecast_balance"],
                "balance_cents": e["forecast_balance_cents"],
                "kind": "estimated" if e.get("estimated") else "known",
            }
            for e in result["events"]
        ],
        completeness={
            "balances_verified": bool(evidence)
            and all(r["balance_verified"] for r in evidence.values()),
            "obligations_complete": not issues,
            "historical_anchor_verified": start >= actual_day,
        },
        explanations=[
            "One canonical event stream; internal cash transfers conserve household cash.",
            "Date-only forecasts apply income, transfers, then expenses. Intraday bank settlement order is not guaranteed.",
        ],
    )
    return result
